version: '2'
services: 
  django-clase-dos:
    # build: .
    image: docker-api-devf
    ports:
      - "8000:8000"
  docker-mysql:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=Mipass_12345
      - MYSQL_DATABASE=danmificadosDb